site_name: Despliegue de aplicaciones web
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: 'slate'  # Este es el esquema oscuro

markdown_extensions:
  - admonition

nav:
  - 'Tema 3': 
    - 'Teoría': 'index.md'
    - 'Prácticas':
      - 'Práctica 3.1 - Tomcat': 'practica1_Tomcat.md'
      - 'Práctica 3.2 - Node Express': 'practica2_NodeExpress.md'