site_name: Prácticas
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: 'slate'  # Este es el esquema oscuro

markdown_extensions:
  - admonition

nav:
  - 'Tema 3': 
    - 'Prácticas':
      - 'Práctica 3.1': 'practica1.md'