site_name: Practicas
site_url: https://mydomain.org/mysite
theme:
  name: 'material'
  palette:
    scheme: 'slate'  # Este es el esquema oscuro

nav:
  - 'Tema3': 
    - 'Prácticas':
      - 'Práctica 3.1': 'practica1.md'